name: Publish Docker images
on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_push:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Retrieve tag name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo TAG_NAME=$(echo $GITHUB_REF | sed -e "s|refs/tags/||") >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ghcr.io/raulcabello/fleet-ui-backend:${{ env.TAG_NAME }}

      - name: Build and push ui
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./ui
          push: true
          tags: ghcr.io/raulcabello/fleet-ui:${{ env.TAG_NAME }}
